export const users = [
    {
        id: 1 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 2 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 3 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 4 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 5 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 6 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 7 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 8 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 9 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 10 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
    {
        id: 11 ,
        name: "Muhammadali",
        age: "24",
        address: "Fergana",
        status: "Magister",
        nickname: "Ali",
        univ: "TATU",
        job: "Developer",
    },
]